### ISSUE TITLE
.htpasswd improperly removed

### ISSUE THREAD

**Issue by Plazmaz** [yannik-b/uberspace-domain-manager#2]
Hello! I noticed your .htpasswd was removed improperly through git. It is currently viewable here https://github.com/yannik-b/uberspace-domain-manager/blob/0c9f5ecf51f43cbdf55f2b2e3fa726780ff283d2/.htpasswd
I suggest you look at https://help.github.com/articles/remove-sensitive-data/ and change your password.

**Comment by yannik-b** [comment]
Hi, thanks for this information.
I removed this file completely, it disappeared in my commit tree also, but your link still works.
Can I delete it?

**Comment by Plazmaz** [comment]
Unfortunately not. This is why you should change your password. It is hashed, but only using MD5. If you use this password elsewhere you should change it there too.

**Comment by yannik-b** [comment]
Ok, thanks for all :)

**Comment by Plazmaz** [comment]
No problem.
